In [112]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/sales_dataset.csv")
df.head()

,Salesperson,Product,Region,Date,Item Unit,No. of Items,Total Sales
0,Diana,Monitor,East,2023-03-26,768.44,11,8452.84
1,Alice,Laptop,East,2023-01-28,138.38,20,2767.60
2,Alice,Laptop,South,2023-04-30,876.50,1,876.50
3,Bob,Monitor,West,2023-01-08,410.97,3,1232.91
4,Carlos,Mobile,South,2023-01-01,1221.02,14,17094.28

In [ ]:
df.isnull().sum()

Salesperson     0
Product         0
Region          0
Item Unit       0
No. of Items    0
Total Sales     0
Month           0
dtype: int64

In [ ]:
df.cloumns =df.columns.str.strip()
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

df['Month'] = df['Date'].dt.month

df = df.drop(columns=['Date'])

In [ ]:
df.head()

  Salesperson  Product Region  Item Unit  No. of Items  Total Sales  Month
0       Diana  Monitor   East     768.44            11      8452.84      3
1       Alice   Laptop   East     138.38            20      2767.60      1
2       Alice   Laptop  South     876.50             1       876.50      4
3         Bob  Monitor   West     410.97             3      1232.91      1
4      Carlos   Mobile  South    1221.02            14     17094.28      1

In [ ]:
from numpy._core import numeric
X = df.drop(columns=['Total Sales'])
y = df['Total Sales']

categorical_columns = ['Salesperson','Product','Region']

In [77]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), categorical_columns)
    ],
    remainder = 'passthrough'
    )

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [98]:
pipeline = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor())
]
)

In [99]:
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

In [100]:
r_score = r2_score(y_test, y_pred)
print("R2 Score : ",r_score)

mean_absoltute = mean_absolute_error(y_test, y_pred)
print("Mean absolute error: ",mean_absoltute)

mean_squared = mean_squared_error(y_test, y_pred)
print("Mean squared error: ",mean_squared)

R2 Score :  0.911815828371185
Mean absolute error:  1088.9307949999993
Mean squared error:  3124692.1563445623

In [110]:
test_data = {
  "Salesperson": "Alice",
  "Product" : "Laptop",
  "Region" : "South",
  "Item Unit" : 1300,
  "No. of Items" : 10,
  "Month": 10
}
predicted_sales = pipeline.predict(pd.DataFrame([test_data]))
print("Predicted sales: ",predicted_sales)

Predicted sales:  [11133.9172]